# Generated by Django 4.2.30 on 2026-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('temple', 'Temple Festival'), ('church', 'Church Feast'), ('mosque', 'Mosque Heritage'), ('dj_music', 'DJ & Music Show'), ('beach_meetup', 'Beach Meetup'), ('arts_culture', 'Arts & Culture'), ('food_fest', 'Food Festival'), ('sports', 'Sports & Games'), ('community', 'Community Gathering'), ('literature', 'Literature & Reading'), ('heritage_walk', 'Heritage Walk'), ('market', 'Local Market'), ('nature_park', 'Nature & Park')], default='community', max_length=50),
        ),
    ]
